# Auto-generated tfvars from existing AWS EKS resources
# Cluster: eks-import-demo-cluster
# Region:  us-east-1
# Generated by EKS Terraform Import Pipeline
# Review and adjust before applying

############################
# General
############################
aws_region   = "us-east-1"
environment  = "dev"
prefix       = "eks-dev"

tags = {
  environment = "dev"
  cloud       = "aws"
  managed_by  = "terraform"
}
