#!/usr/bin/env python3
"""
Generates tfvars file from discovered EKS + VPC resources.
"""
import json, os

with open('/tmp/eks-resources.json') as f:
    resources = json.load(f)

cluster_name    = os.environ.get('CLUSTER_NAME', '')
environment     = os.environ.get('ENVIRONMENT', 'dev')
aws_region      = os.environ.get('AWS_REGION', 'us-east-1')

# Build lookup by type
by_type = {}
for r in resources:
    t = r['type']
    if t not in by_type:
        by_type[t] = []
    by_type[t].append(r)

vpc       = by_type.get('aws_vpc', [{}])[0]
subnets   = by_type.get('aws_subnet', [])
eks       = by_type.get('aws_eks_cluster', [{}])[0]
nodegroups = by_type.get('aws_eks_node_group', [])

private_subnets = [s for s in subnets
                   if any(t.get('Key') == 'kubernetes.io/role/internal-elb'
                          for t in s.get('details', {}).get('tags', []))]
public_subnets  = [s for s in subnets if s not in private_subnets]

lines = []
lines.append('# Auto-generated tfvars from existing AWS EKS resources')
lines.append(f'# Cluster: {cluster_name}')
lines.append(f'# Region:  {aws_region}')
lines.append('# Generated by EKS Terraform Import Pipeline')
lines.append('# Review and adjust before applying')
lines.append('')

# General
lines.append('############################')
lines.append('# General')
lines.append('############################')
lines.append(f'aws_region   = "{aws_region}"')
lines.append(f'environment  = "{environment}"')
lines.append(f'prefix       = "eks-{environment}"')
lines.append('')
lines.append('tags = {')
lines.append(f'  environment = "{environment}"')
lines.append('  cloud       = "aws"')
lines.append('  managed_by  = "terraform"')
lines.append('}')
lines.append('')

# VPC
if vpc:
    d = vpc.get('details', {})
    lines.append('############################')
    lines.append('# VPC')
    lines.append('############################')
    lines.append(f'vpc_name = "{vpc.get("name", "")}"')
    lines.append(f'vpc_cidr = "{d.get("cidr_block", "10.0.0.0/16")}"')
    lines.append('')

    # Subnets
    if subnets:
        private_cidrs = [s['details']['cidr_block'] for s in subnets
                         if 'private' in s['name'].lower() or 'priv' in s['name'].lower()]
        public_cidrs  = [s['details']['cidr_block'] for s in subnets
                         if 'public' in s['name'].lower() or 'pub' in s['name'].lower()]
        azs = list(set(s['details']['availability_zone'] for s in subnets))

        lines.append(f'availability_zones = {json.dumps(sorted(azs))}')
        if private_cidrs:
            lines.append(f'private_subnet_cidrs = {json.dumps(private_cidrs)}')
        if public_cidrs:
            lines.append(f'public_subnet_cidrs = {json.dumps(public_cidrs)}')
        lines.append('')
        lines.append('# All discovered subnets:')
        for s in subnets:
            lines.append(f'#   {s["name"]}: {s["details"]["cidr_block"]} ({s["details"]["availability_zone"]})')
        lines.append('')

# EKS
if eks:
    d = eks.get('details', {})
    lines.append('############################')
    lines.append('# EKS')
    lines.append('############################')
    lines.append(f'cluster_name           = "{eks.get("name", cluster_name)}"')
    lines.append(f'kubernetes_version     = "{d.get("version", "1.36")}"')
    lines.append(f'endpoint_public_access = true')
    lines.append(f'node_volume_size_gb    = 50')
    lines.append('')

# Node Groups
if nodegroups:
    lines.append('############################')
    lines.append('# Node Groups')
    lines.append('############################')
    for ng in nodegroups:
        d = ng.get('details', {})
        ng_name = ng['name']
        lines.append(f'# Node group: {ng_name}')
        if 'system' in ng_name.lower():
            lines.append(f'enable_system_node_group   = true')
            lines.append(f'system_node_instance_types = {json.dumps(d.get("instance_types", ["t3.medium"]))}')
            lines.append(f'system_node_desired        = {d.get("desired_size", 1)}')
            lines.append(f'system_node_min            = {d.get("min_size", 1)}')
            lines.append(f'system_node_max            = {d.get("max_size", 3)}')
        else:
            lines.append(f'enable_system_node_group  = false')
            lines.append(f'user_node_instance_types  = {json.dumps(d.get("instance_types", ["t3.large"]))}')
            lines.append(f'user_node_desired         = {d.get("desired_size", 1)}')
            lines.append(f'user_node_min             = {d.get("min_size", 1)}')
            lines.append(f'user_node_max             = {d.get("max_size", 5)}')
        lines.append('')

content = '\n'.join(lines)
with open('/tmp/generated.tfvars', 'w') as f:
    f.write(content)

print("Generated tfvars:")
print("=" * 50)
print(content)
print("=" * 50)
print(f"\nSaved to /tmp/generated.tfvars")
