# Auto-generated tfvars from existing Azure resources
# Resource Group: rg-import-demo
# Generated by Azure Terraform Import Pipeline
# Review and adjust values before applying

############################
# General
############################
subscription_id     = "a87e6cba-3f02-47fb-9c7d-755704a0cde2"
resource_group_name = "rg-import-demo"
environment         = "dev"

tags = {
  environment = "demo"
  managed_by = "cli"
}

############################
# VNet
############################
vnet_name = "vnet-import-demo"
vnet_cidr = "10.0.0.0/8"

# Subnet CIDRs
# import-demo-snet-storage: 10.0.32.0/24
# import-demo-snet-aks: 10.0.0.0/20

############################
# NSG
############################
# nsg_name = "import-demo-nsg"
# location  = "eastus"

############################
# Key Vault
############################
key_vault_name                    = "kv-import-demo-mridul2"
location                           = "eastus"
kv_sku_name                        = "standard"
kv_soft_delete_retention_days     = 90
kv_purge_protection_enabled       = true
kv_public_network_access_enabled  = true

############################
# Storage Account
############################
storage_account_name     = "stimportdemomridul"
storage_replication_type = "LRS"
# storage_account_tier  = "Standard"
