#!/usr/bin/env python3
"""
Reads discovered Azure resources and generates a tfvars file
matching the variable structure of our existing Terraform modules.
"""
import json
import os
import sys

rg = os.environ.get('RESOURCE_GROUP', '')
subscription_id = os.environ.get('SUBSCRIPTION_ID', '')
environment = os.environ.get('ENVIRONMENT', 'dev')

with open('/tmp/all-resources.json') as f:
    resources = json.load(f)

# Build lookup by type
by_type = {}
for r in resources:
    rtype = r['type'].lower()
    if rtype not in by_type:
        by_type[rtype] = []
    by_type[rtype].append(r)

def get(rtype):
    return by_type.get(rtype, [])

# Extract values per resource type
vnet      = get('microsoft.network/virtualnetworks')
nsg       = get('microsoft.network/networksecuritygroups')
kv        = get('microsoft.keyvault/vaults')
storage   = get('microsoft.storage/storageaccounts')
aks       = get('microsoft.containerservice/managedclusters')

lines = []
lines.append(f'# Auto-generated tfvars from existing Azure resources')
lines.append(f'# Resource Group: {rg}')
lines.append(f'# Generated by Azure Terraform Import Pipeline')
lines.append(f'# Review and adjust values before applying')
lines.append('')

# General
lines.append('############################')
lines.append('# General')
lines.append('############################')
lines.append(f'subscription_id     = "{subscription_id}"')
lines.append(f'resource_group_name = "{rg}"')
lines.append(f'environment         = "{environment}"')
lines.append('')

# Tags from first resource
tags = resources[0].get('tags', {}) if resources else {}
if tags:
    lines.append('tags = {')
    for k, v in tags.items():
        lines.append(f'  {k} = "{v}"')
    lines.append('}')
    lines.append('')

# VNet
if vnet:
    v = vnet[0]
    props = v.get('properties', {})
    addr  = props.get('addressSpace', {}).get('addressPrefixes', ['10.0.0.0/8'])
    lines.append('############################')
    lines.append('# VNet')
    lines.append('############################')
    lines.append(f'vnet_name = "{v["name"]}"')
    lines.append(f'vnet_cidr = "{addr[0] if addr else "10.0.0.0/8"}"')
    lines.append('')

    # Subnets
    subnets = props.get('subnets', [])
    if subnets:
        lines.append('# Subnet CIDRs')
        for s in subnets:
            sname  = s.get('name', '')
            scidr  = s.get('properties', {}).get('addressPrefix', '')
            svar   = sname.replace('-', '_').replace(' ', '_')
            lines.append(f'# {sname}: {scidr}')
        lines.append('')

# NSG
if nsg:
    n = nsg[0]
    lines.append('############################')
    lines.append('# NSG')
    lines.append('############################')
    lines.append(f'# nsg_name = "{n["name"]}"')
    lines.append(f'# location  = "{n.get("location", "eastus")}"')
    lines.append('')

# Key Vault
if kv:
    k = kv[0]
    props = k.get('properties', {})
    lines.append('############################')
    lines.append('# Key Vault')
    lines.append('############################')
    lines.append(f'key_vault_name                    = "{k["name"]}"')
    lines.append(f'location                           = "{k.get("location", "eastus")}"')
    lines.append(f'kv_sku_name                        = "{props.get("sku", {}).get("name", "standard")}"')
    lines.append(f'kv_soft_delete_retention_days     = {props.get("softDeleteRetentionInDays", 90)}')
    lines.append(f'kv_purge_protection_enabled       = {str(props.get("enablePurgeProtection", True)).lower()}')
    lines.append(f'kv_public_network_access_enabled  = {str(props.get("publicNetworkAccess", "Enabled") == "Enabled").lower()}')
    lines.append('')

# Storage Account
if storage:
    s = storage[0]
    props = s.get('properties', {})
    sku   = s.get('sku', {})
    lines.append('############################')
    lines.append('# Storage Account')
    lines.append('############################')
    lines.append(f'storage_account_name     = "{s["name"]}"')
    lines.append(f'storage_replication_type = "{sku.get("name", "LRS").split("_")[-1]}"')
    lines.append(f'# storage_account_tier  = "{sku.get("tier", "Standard")}"')
    lines.append('')

# AKS
if aks:
    a = aks[0]
    props = a.get('properties', {})
    lines.append('############################')
    lines.append('# AKS')
    lines.append('############################')
    lines.append(f'cluster_name       = "{a["name"]}"')
    lines.append(f'dns_prefix         = "{props.get("dnsPrefix", a["name"])}"')
    lines.append(f'kubernetes_version = "{props.get("kubernetesVersion", "1.32")}"')

    # Node pools
    agent_pools = props.get('agentPoolProfiles', [])
    for pool in agent_pools:
        pname = pool.get('name', 'nodepool')
        lines.append(f'# Node pool: {pname}')
        lines.append(f'#   vm_size  = "{pool.get("vmSize", "Standard_D2s_v3")}"')
        lines.append(f'#   count    = {pool.get("count", 1)}')
        lines.append(f'#   mode     = "{pool.get("mode", "System")}"')
    lines.append('')

# Output
tfvars_content = '\n'.join(lines)
with open('/tmp/generated.tfvars', 'w') as f:
    f.write(tfvars_content)

print("Generated tfvars:")
print("=" * 50)
print(tfvars_content)
print("=" * 50)
print(f"\nSaved to /tmp/generated.tfvars")
